### ISSUE TITLE
About some of the tech tree does not work

### ISSUE THREAD

**Issue by shenghaojin12** [karelpak1/WoTB_Extended_Tech_Tree#1]
Hi, I tried on all 9.9 9.8 and 9.7 release, the france, german, usa and british tech tree are not working, the rest works fine

![KG8)TGB~Z2VZFUC06BO7@}W](https://user-images.githubusercontent.com/44574403/236973250-c563caab-02be-46da-ad5f-e8bded9799f4.png)
![M{81K73JOWF7Y7~ LC)K EY](https://user-images.githubusercontent.com/44574403/236973283-04057d67-7ae5-4f0a-a3c1-5b4ba8fb09a6.png)
![R2${ %O9O1$CT9WYHB_ $RR](https://user-images.githubusercontent.com/44574403/236973333-32cdd503-93a6-4157-9a66-9f4bda9f0e00.png)
![B1V2NC `A6JMW{2_GWR)%~N](https://user-images.githubusercontent.com/44574403/236973359-41a8aeb0-2391-4a59-a3bb-9496c485341a.png)

**Comment by karelpak1** [comment]
Hi, what device do you use? And what platform are you using (android, iOS, macOS steam, Windows Steam, Windows Store)? And how your mod was installed?

**Comment by shenghaojin12** [comment]
Im on PC with steam, and I did this to install 
![image](https://github.com/karelpak1/WoTB_Extended_Tech_Tree/assets/44574403/7dbefeb4-adf2-4a53-84d9-902ba24a6046)

**Comment by karelpak1** [comment]
Sorry, try to install mod in to %username%/documents/packs folder, because patch was released via smartDLC feature.

**Comment by shenghaojin12** [comment]
cool let me try, and will the 9.9 version work now? or should i use the 9.8?

**Comment by karelpak1** [comment]
Please use 9.9.

**Comment by shenghaojin12** [comment]
it worked, thank you~

**Comment by LosTSouL-ru** [comment]
я играю через Lesta на компьютере, и ваш способ   %username% / documents / packs  не работает, есть более подробная инструкция ?
