### ISSUE TITLE
TB_Extended_Tech_Tree

### ISSUE THREAD

**Issue by LosTSouL-ru** [karelpak1/WoTB_Extended_Tech_Tree#3]
привет можешь подсказать как самому изменить файлы, а то пытался а танки в дереве изучений не появляются, может я что то пропускаю ?

**Comment by karelpak1** [comment]
Hello, duplicate of #1

**Comment by LosTSouL-ru** [comment]
я играю через Lesta на компьютере, и ваш способ %username% / documents / packs не работает, есть более подробная инструкция ?
