### ISSUE TITLE
Add hybrid nation

### ISSUE THREAD

**Issue by LosTSouL-ru** [karelpak1/WoTB_Extended_Tech_Tree#4]
is it possible to do this?
![Снимок экрана 2023-12-30 015623](https://github.com/karelpak1/WoTB_Extended_Tech_Tree/assets/155009950/cbaabd25-0213-4f5d-b8bd-5c0e8c02b5b1)

**Comment by karelpak1** [comment]
Hello, it is not possible to add a separate nation on the left. 
Adding hybrid tanks in to any nation is "possible", but when you click on it, game crashes.

**Comment by 4a4man** [comment]
Hello! How fix this? tree was empty =(
![image](https://github.com/karelpak1/WoTB_Extended_Tech_Tree/assets/155373851/83ee4763-8d51-492d-898e-8a64b9f6f15d)

**Comment by LosTSouL-ru** [comment]
заново поменяй файлы ,  так как было микро обновление

**Comment by 4a4man** [comment]
> заново поменяй файлы , так как было микро обновление

не помогло, такая же проблема

**Comment by LosTSouL-ru** [comment]
![Снимок экрана 2024-01-01 210024](https://github.com/karelpak1/WoTB_Extended_Tech_Tree/assets/155009950/8a0d45be-766d-45cc-9002-b3a2159fb47a)
![Снимок экрана 2024-01-01 210113](https://github.com/karelpak1/WoTB_Extended_Tech_Tree/assets/155009950/8670dfb4-9f97-480e-93c8-f2604ebc568c)
![Снимок экрана 2024-01-01 210237](https://github.com/karelpak1/WoTB_Extended_Tech_Tree/assets/155009950/c7918511-776c-40f9-94b1-23fa98f55a90)

я закинул C:\Users\*nameuser*\OneDrive\Документы\packs и  C:\Tanks_Blitz\Data и у меня работает

**Comment by LosTSouL-ru** [comment]
![Снимок экрана 2024-01-01 211440](https://github.com/karelpak1/WoTB_Extended_Tech_Tree/assets/155009950/41797db2-ffcd-429c-9739-aca3e13928a5)
![2024-01-01_21-15-36](https://github.com/karelpak1/WoTB_Extended_Tech_Tree/assets/155009950/2f11c493-e516-4bda-bd87-bdac885153df)

 так как ты на вг через стим  то у тебя надо брать другие  файлы и также в документы и C:\Program Files (x86)\Steam\steamapps\common\World of Tanks Blitz  закидывать и как видишь тоже работает

**Comment by karelpak1** [comment]
Update regarding this request, probably during this day, I'll add this feature (Hybrid Nation) for Wargaming and tomorrow for Lesta.
Because a lot of changes between Tanks Blitz and World of Tanks Blitz, I separated repositories to two.

Wargaming (WoTB) repository will be this one.
Lesta (TB) repository is already available in this [repository](https://github.com/karelpak1/TB_ETT)
